### PR TITLE
fixed bug in calculation for doublet stat .csv

### PR DESCRIPTION
**Pull request by erflynn**
one-line fix to address bug in `doublet_counts.csv` that @syellamilli identified

### CODE REVIEW

**Comment by erflynn** [comment]
@dtm2451  tagging you b/c it may affect your work. Some of the doublet calculations are wrong in the `doublet_count.csv`. They are still in the `doublet_stat.RDS`. I recommend just deleting these .csvs.

**Comment by erflynn** [comment]
from more investigation with @syellamilli, it appears this was introduced in commit 4e1e4d3 but not caught until now. will run a couple more comparisons to confirm this is fixed before submitting PR

**Comment by erflynn** [comment]
comparisons done, and output confirmed. I would like to merge this in ASAP if folks are ok with

**Review by amadeovezz — APPROVED** [review]
lgtm!

**Pull request merged**
